// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AssetTag struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	VariantID pgtype.UUID        `db:"variant_id" json:"variant_id"`
	Tag       string             `db:"tag" json:"tag"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Brand struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	WorkspaceID      pgtype.UUID        `db:"workspace_id" json:"workspace_id"`
	Name             string             `db:"name" json:"name"`
	LogoR2Key        *string            `db:"logo_r2_key" json:"logo_r2_key"`
	PrimaryColor     string             `db:"primary_color" json:"primary_color"`
	SecondaryColor   *string            `db:"secondary_color" json:"secondary_color"`
	FontFamily       *string            `db:"font_family" json:"font_family"`
	WatermarkEnabled bool               `db:"watermark_enabled" json:"watermark_enabled"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Brief struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	WorkspaceID pgtype.UUID        `db:"workspace_id" json:"workspace_id"`
	ScrapeJobID pgtype.UUID        `db:"scrape_job_id" json:"scrape_job_id"`
	ProductUrl  string             `db:"product_url" json:"product_url"`
	Model       string             `db:"model" json:"model"`
	Status      string             `db:"status" json:"status"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type BriefAngle struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	BriefID   pgtype.UUID        `db:"brief_id" json:"brief_id"`
	Angle     string             `db:"angle" json:"angle"`
	Headline  string             `db:"headline" json:"headline"`
	Script    string             `db:"script" json:"script"`
	Cta       string             `db:"cta" json:"cta"`
	VoiceTone *string            `db:"voice_tone" json:"voice_tone"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type BriefHook struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	BriefID   pgtype.UUID        `db:"brief_id" json:"brief_id"`
	Hook      string             `db:"hook" json:"hook"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Export struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	WorkspaceID pgtype.UUID        `db:"workspace_id" json:"workspace_id"`
	VariantID   pgtype.UUID        `db:"variant_id" json:"variant_id"`
	Destination string             `db:"destination" json:"destination"`
	Status      string             `db:"status" json:"status"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Job struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	WorkspaceID pgtype.UUID        `db:"workspace_id" json:"workspace_id"`
	ProductUrl  string             `db:"product_url" json:"product_url"`
	Status      string             `db:"status" json:"status"`
	Model       string             `db:"model" json:"model"`
	BriefJson   []byte             `db:"brief_json" json:"brief_json"`
	ErrorMsg    *string            `db:"error_msg" json:"error_msg"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Variant struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	JobID         pgtype.UUID        `db:"job_id" json:"job_id"`
	WorkspaceID   pgtype.UUID        `db:"workspace_id" json:"workspace_id"`
	Angle         string             `db:"angle" json:"angle"`
	Status        string             `db:"status" json:"status"`
	FalRequestID  *string            `db:"fal_request_id" json:"fal_request_id"`
	MuxAssetID    *string            `db:"mux_asset_id" json:"mux_asset_id"`
	MuxPlaybackID *string            `db:"mux_playback_id" json:"mux_playback_id"`
	R2Key         *string            `db:"r2_key" json:"r2_key"`
	DurationSecs  pgtype.Numeric     `db:"duration_secs" json:"duration_secs"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Workspace struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	OrgID       string             `db:"org_id" json:"org_id"`
	PlanTier    string             `db:"plan_tier" json:"plan_tier"`
	SubStatus   string             `db:"sub_status" json:"sub_status"`
	StripeSubID *string            `db:"stripe_sub_id" json:"stripe_sub_id"`
	TrialEndsAt pgtype.Timestamptz `db:"trial_ends_at" json:"trial_ends_at"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
