// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: perf_cost.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJobIdempotent = `-- name: CreateJobIdempotent :one
INSERT INTO jobs (
  workspace_id, product_url, status, model, idempotency_key
) VALUES (
  $1, $2, 'queued', $3, $4
)
ON CONFLICT (workspace_id, idempotency_key)
WHERE idempotency_key IS NOT NULL
DO UPDATE SET updated_at = NOW()
RETURNING id, workspace_id, product_url, status, model, brief_json, error_msg, created_at, updated_at, idempotency_key
`

type CreateJobIdempotentParams struct {
	WorkspaceID    pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	ProductUrl     string      `db:"product_url" json:"product_url"`
	Model          string      `db:"model" json:"model"`
	IdempotencyKey *string     `db:"idempotency_key" json:"idempotency_key"`
}

// ON CONFLICT returns the existing row — client gets the same job_id on retry.
func (q *Queries) CreateJobIdempotent(ctx context.Context, arg CreateJobIdempotentParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJobIdempotent,
		arg.WorkspaceID,
		arg.ProductUrl,
		arg.Model,
		arg.IdempotencyKey,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProductUrl,
		&i.Status,
		&i.Model,
		&i.BriefJson,
		&i.ErrorMsg,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const getWorkspaceMonthCost = `-- name: GetWorkspaceMonthCost :one
SELECT COALESCE(SUM(estimated_usd), 0)::NUMERIC AS total_usd
FROM cost_events
WHERE workspace_id = $1
  AND date_trunc('month', recorded_at) = date_trunc('month', NOW())
`

func (q *Queries) GetWorkspaceMonthCost(ctx context.Context, workspaceID pgtype.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getWorkspaceMonthCost, workspaceID)
	var total_usd pgtype.Numeric
	err := row.Scan(&total_usd)
	return total_usd, err
}

const insertCostEvent = `-- name: InsertCostEvent :exec
INSERT INTO cost_events (
  workspace_id, variant_id, job_id,
  source, model,
  estimated_usd, credits, recorded_at
) VALUES (
  $1, $2, $3,
  $4, $5,
  $6, $7, $8
)
`

type InsertCostEventParams struct {
	WorkspaceID  pgtype.UUID        `db:"workspace_id" json:"workspace_id"`
	VariantID    pgtype.UUID        `db:"variant_id" json:"variant_id"`
	JobID        pgtype.UUID        `db:"job_id" json:"job_id"`
	Source       string             `db:"source" json:"source"`
	Model        *string            `db:"model" json:"model"`
	EstimatedUsd pgtype.Numeric     `db:"estimated_usd" json:"estimated_usd"`
	Credits      int32              `db:"credits" json:"credits"`
	RecordedAt   pgtype.Timestamptz `db:"recorded_at" json:"recorded_at"`
}

func (q *Queries) InsertCostEvent(ctx context.Context, arg InsertCostEventParams) error {
	_, err := q.db.Exec(ctx, insertCostEvent,
		arg.WorkspaceID,
		arg.VariantID,
		arg.JobID,
		arg.Source,
		arg.Model,
		arg.EstimatedUsd,
		arg.Credits,
		arg.RecordedAt,
	)
	return err
}

const insertPerfEvent = `-- name: InsertPerfEvent :exec
INSERT INTO video_performance_events (
  workspace_id, variant_id, job_id,
  stage, duration_ms, model,
  fal_request_id, error_type, error_msg, recorded_at
) VALUES (
  $1, $2, $3,
  $4, $5, $6,
  $7, $8, $9, $10
)
`

type InsertPerfEventParams struct {
	WorkspaceID  pgtype.UUID        `db:"workspace_id" json:"workspace_id"`
	VariantID    pgtype.UUID        `db:"variant_id" json:"variant_id"`
	JobID        pgtype.UUID        `db:"job_id" json:"job_id"`
	Stage        string             `db:"stage" json:"stage"`
	DurationMs   int32              `db:"duration_ms" json:"duration_ms"`
	Model        *string            `db:"model" json:"model"`
	FalRequestID *string            `db:"fal_request_id" json:"fal_request_id"`
	ErrorType    *string            `db:"error_type" json:"error_type"`
	ErrorMsg     *string            `db:"error_msg" json:"error_msg"`
	RecordedAt   pgtype.Timestamptz `db:"recorded_at" json:"recorded_at"`
}

func (q *Queries) InsertPerfEvent(ctx context.Context, arg InsertPerfEventParams) error {
	_, err := q.db.Exec(ctx, insertPerfEvent,
		arg.WorkspaceID,
		arg.VariantID,
		arg.JobID,
		arg.Stage,
		arg.DurationMs,
		arg.Model,
		arg.FalRequestID,
		arg.ErrorType,
		arg.ErrorMsg,
		arg.RecordedAt,
	)
	return err
}

const listPerfEventsByVariant = `-- name: ListPerfEventsByVariant :many
SELECT stage, duration_ms, model, fal_request_id, error_type, recorded_at
FROM video_performance_events
WHERE variant_id = $1
ORDER BY recorded_at ASC
`

type ListPerfEventsByVariantRow struct {
	Stage        string             `db:"stage" json:"stage"`
	DurationMs   int32              `db:"duration_ms" json:"duration_ms"`
	Model        *string            `db:"model" json:"model"`
	FalRequestID *string            `db:"fal_request_id" json:"fal_request_id"`
	ErrorType    *string            `db:"error_type" json:"error_type"`
	RecordedAt   pgtype.Timestamptz `db:"recorded_at" json:"recorded_at"`
}

func (q *Queries) ListPerfEventsByVariant(ctx context.Context, variantID pgtype.UUID) ([]ListPerfEventsByVariantRow, error) {
	rows, err := q.db.Query(ctx, listPerfEventsByVariant, variantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPerfEventsByVariantRow{}
	for rows.Next() {
		var i ListPerfEventsByVariantRow
		if err := rows.Scan(
			&i.Stage,
			&i.DurationMs,
			&i.Model,
			&i.FalRequestID,
			&i.ErrorType,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVariantAvatarJob = `-- name: UpdateVariantAvatarJob :exec
UPDATE variants
SET avatar_job_id    = $2,
    avatar_provider  = $3,
    updated_at       = NOW()
WHERE id = $1
`

type UpdateVariantAvatarJobParams struct {
	ID             pgtype.UUID `db:"id" json:"id"`
	AvatarJobID    *string     `db:"avatar_job_id" json:"avatar_job_id"`
	AvatarProvider *string     `db:"avatar_provider" json:"avatar_provider"`
}

func (q *Queries) UpdateVariantAvatarJob(ctx context.Context, arg UpdateVariantAvatarJobParams) error {
	_, err := q.db.Exec(ctx, updateVariantAvatarJob, arg.ID, arg.AvatarJobID, arg.AvatarProvider)
	return err
}
