// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (workspace_id, product_url, model)
VALUES ($1, $2, $3)
RETURNING id, workspace_id, product_url, status, model, brief_json, error_msg, created_at, updated_at
`

type CreateJobParams struct {
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	ProductUrl  string      `db:"product_url" json:"product_url"`
	Model       string      `db:"model" json:"model"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob, arg.WorkspaceID, arg.ProductUrl, arg.Model)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProductUrl,
		&i.Status,
		&i.Model,
		&i.BriefJson,
		&i.ErrorMsg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVariant = `-- name: CreateVariant :one
INSERT INTO variants (job_id, workspace_id, angle)
VALUES ($1, $2, $3)
RETURNING id, job_id, workspace_id, angle, status, fal_request_id, mux_asset_id, mux_playback_id, r2_key, duration_secs, created_at, updated_at
`

type CreateVariantParams struct {
	JobID       pgtype.UUID `db:"job_id" json:"job_id"`
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	Angle       string      `db:"angle" json:"angle"`
}

func (q *Queries) CreateVariant(ctx context.Context, arg CreateVariantParams) (Variant, error) {
	row := q.db.QueryRow(ctx, createVariant, arg.JobID, arg.WorkspaceID, arg.Angle)
	var i Variant
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.WorkspaceID,
		&i.Angle,
		&i.Status,
		&i.FalRequestID,
		&i.MuxAssetID,
		&i.MuxPlaybackID,
		&i.R2Key,
		&i.DurationSecs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobByID = `-- name: GetJobByID :one
SELECT id, workspace_id, product_url, status, model, brief_json, error_msg, created_at, updated_at FROM jobs
WHERE id = $1 AND workspace_id = $2
LIMIT 1
`

type GetJobByIDParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
}

func (q *Queries) GetJobByID(ctx context.Context, arg GetJobByIDParams) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByID, arg.ID, arg.WorkspaceID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProductUrl,
		&i.Status,
		&i.Model,
		&i.BriefJson,
		&i.ErrorMsg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceByOrgID = `-- name: GetWorkspaceByOrgID :one
SELECT id, org_id, plan_tier, sub_status, stripe_sub_id, trial_ends_at, created_at, updated_at FROM workspaces
WHERE org_id = $1
LIMIT 1
`

func (q *Queries) GetWorkspaceByOrgID(ctx context.Context, orgID string) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByOrgID, orgID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.PlanTier,
		&i.SubStatus,
		&i.StripeSubID,
		&i.TrialEndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJobsByWorkspace = `-- name: ListJobsByWorkspace :many
SELECT id, workspace_id, product_url, status, model, brief_json, error_msg, created_at, updated_at FROM jobs
WHERE workspace_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListJobsByWorkspaceParams struct {
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	Limit       int32       `db:"limit" json:"limit"`
	Offset      int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListJobsByWorkspace(ctx context.Context, arg ListJobsByWorkspaceParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByWorkspace, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProductUrl,
			&i.Status,
			&i.Model,
			&i.BriefJson,
			&i.ErrorMsg,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantsByJob = `-- name: ListVariantsByJob :many
SELECT id, job_id, workspace_id, angle, status, fal_request_id, mux_asset_id, mux_playback_id, r2_key, duration_secs, created_at, updated_at FROM variants
WHERE job_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListVariantsByJob(ctx context.Context, jobID pgtype.UUID) ([]Variant, error) {
	rows, err := q.db.Query(ctx, listVariantsByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Variant{}
	for rows.Next() {
		var i Variant
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.WorkspaceID,
			&i.Angle,
			&i.Status,
			&i.FalRequestID,
			&i.MuxAssetID,
			&i.MuxPlaybackID,
			&i.R2Key,
			&i.DurationSecs,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobStatus = `-- name: UpdateJobStatus :one
UPDATE jobs
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, workspace_id, product_url, status, model, brief_json, error_msg, created_at, updated_at
`

type UpdateJobStatusParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	Status string      `db:"status" json:"status"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJobStatus, arg.ID, arg.Status)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProductUrl,
		&i.Status,
		&i.Model,
		&i.BriefJson,
		&i.ErrorMsg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVariantComplete = `-- name: UpdateVariantComplete :one
UPDATE variants
SET status = 'complete',
    mux_asset_id    = $2,
    mux_playback_id = $3,
    r2_key          = $4,
    duration_secs   = $5,
    updated_at      = NOW()
WHERE id = $1
RETURNING id, job_id, workspace_id, angle, status, fal_request_id, mux_asset_id, mux_playback_id, r2_key, duration_secs, created_at, updated_at
`

type UpdateVariantCompleteParams struct {
	ID            pgtype.UUID    `db:"id" json:"id"`
	MuxAssetID    *string        `db:"mux_asset_id" json:"mux_asset_id"`
	MuxPlaybackID *string        `db:"mux_playback_id" json:"mux_playback_id"`
	R2Key         *string        `db:"r2_key" json:"r2_key"`
	DurationSecs  pgtype.Numeric `db:"duration_secs" json:"duration_secs"`
}

func (q *Queries) UpdateVariantComplete(ctx context.Context, arg UpdateVariantCompleteParams) (Variant, error) {
	row := q.db.QueryRow(ctx, updateVariantComplete,
		arg.ID,
		arg.MuxAssetID,
		arg.MuxPlaybackID,
		arg.R2Key,
		arg.DurationSecs,
	)
	var i Variant
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.WorkspaceID,
		&i.Angle,
		&i.Status,
		&i.FalRequestID,
		&i.MuxAssetID,
		&i.MuxPlaybackID,
		&i.R2Key,
		&i.DurationSecs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertWorkspace = `-- name: UpsertWorkspace :one
INSERT INTO workspaces (org_id, plan_tier, sub_status, trial_ends_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (org_id) DO UPDATE SET
    plan_tier     = EXCLUDED.plan_tier,
    sub_status    = EXCLUDED.sub_status,
    trial_ends_at = EXCLUDED.trial_ends_at,
    updated_at    = NOW()
RETURNING id, org_id, plan_tier, sub_status, stripe_sub_id, trial_ends_at, created_at, updated_at
`

type UpsertWorkspaceParams struct {
	OrgID       string             `db:"org_id" json:"org_id"`
	PlanTier    string             `db:"plan_tier" json:"plan_tier"`
	SubStatus   string             `db:"sub_status" json:"sub_status"`
	TrialEndsAt pgtype.Timestamptz `db:"trial_ends_at" json:"trial_ends_at"`
}

func (q *Queries) UpsertWorkspace(ctx context.Context, arg UpsertWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, upsertWorkspace,
		arg.OrgID,
		arg.PlanTier,
		arg.SubStatus,
		arg.TrialEndsAt,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.PlanTier,
		&i.SubStatus,
		&i.StripeSubID,
		&i.TrialEndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
