// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBrief = `-- name: CreateBrief :one
INSERT INTO briefs (workspace_id, scrape_job_id, product_url, model, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workspace_id, scrape_job_id, product_url, model, status, created_at, updated_at
`

type CreateBriefParams struct {
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	ScrapeJobID pgtype.UUID `db:"scrape_job_id" json:"scrape_job_id"`
	ProductUrl  string      `db:"product_url" json:"product_url"`
	Model       string      `db:"model" json:"model"`
	Status      string      `db:"status" json:"status"`
}

func (q *Queries) CreateBrief(ctx context.Context, arg CreateBriefParams) (Brief, error) {
	row := q.db.QueryRow(ctx, createBrief,
		arg.WorkspaceID,
		arg.ScrapeJobID,
		arg.ProductUrl,
		arg.Model,
		arg.Status,
	)
	var i Brief
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ScrapeJobID,
		&i.ProductUrl,
		&i.Model,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBriefAngle = `-- name: CreateBriefAngle :one
INSERT INTO brief_angles (brief_id, angle, headline, script, cta, voice_tone)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, brief_id, angle, headline, script, cta, voice_tone, created_at
`

type CreateBriefAngleParams struct {
	BriefID   pgtype.UUID `db:"brief_id" json:"brief_id"`
	Angle     string      `db:"angle" json:"angle"`
	Headline  string      `db:"headline" json:"headline"`
	Script    string      `db:"script" json:"script"`
	Cta       string      `db:"cta" json:"cta"`
	VoiceTone *string     `db:"voice_tone" json:"voice_tone"`
}

func (q *Queries) CreateBriefAngle(ctx context.Context, arg CreateBriefAngleParams) (BriefAngle, error) {
	row := q.db.QueryRow(ctx, createBriefAngle,
		arg.BriefID,
		arg.Angle,
		arg.Headline,
		arg.Script,
		arg.Cta,
		arg.VoiceTone,
	)
	var i BriefAngle
	err := row.Scan(
		&i.ID,
		&i.BriefID,
		&i.Angle,
		&i.Headline,
		&i.Script,
		&i.Cta,
		&i.VoiceTone,
		&i.CreatedAt,
	)
	return i, err
}

const createBriefHook = `-- name: CreateBriefHook :one
INSERT INTO brief_hooks (brief_id, hook)
VALUES ($1, $2)
RETURNING id, brief_id, hook, created_at
`

type CreateBriefHookParams struct {
	BriefID pgtype.UUID `db:"brief_id" json:"brief_id"`
	Hook    string      `db:"hook" json:"hook"`
}

func (q *Queries) CreateBriefHook(ctx context.Context, arg CreateBriefHookParams) (BriefHook, error) {
	row := q.db.QueryRow(ctx, createBriefHook, arg.BriefID, arg.Hook)
	var i BriefHook
	err := row.Scan(
		&i.ID,
		&i.BriefID,
		&i.Hook,
		&i.CreatedAt,
	)
	return i, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (workspace_id, product_url, model)
VALUES ($1, $2, $3)
RETURNING id, workspace_id, product_url, status, model, brief_json, error_msg, created_at, updated_at, idempotency_key
`

type CreateJobParams struct {
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	ProductUrl  string      `db:"product_url" json:"product_url"`
	Model       string      `db:"model" json:"model"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob, arg.WorkspaceID, arg.ProductUrl, arg.Model)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProductUrl,
		&i.Status,
		&i.Model,
		&i.BriefJson,
		&i.ErrorMsg,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const createVariant = `-- name: CreateVariant :one
INSERT INTO variants (job_id, workspace_id, angle)
VALUES ($1, $2, $3)
RETURNING id, job_id, workspace_id, angle, status, fal_request_id, mux_asset_id, mux_playback_id, r2_key, duration_secs, created_at, updated_at, avatar_provider, avatar_job_id
`

type CreateVariantParams struct {
	JobID       pgtype.UUID `db:"job_id" json:"job_id"`
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	Angle       string      `db:"angle" json:"angle"`
}

func (q *Queries) CreateVariant(ctx context.Context, arg CreateVariantParams) (Variant, error) {
	row := q.db.QueryRow(ctx, createVariant, arg.JobID, arg.WorkspaceID, arg.Angle)
	var i Variant
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.WorkspaceID,
		&i.Angle,
		&i.Status,
		&i.FalRequestID,
		&i.MuxAssetID,
		&i.MuxPlaybackID,
		&i.R2Key,
		&i.DurationSecs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvatarProvider,
		&i.AvatarJobID,
	)
	return i, err
}

const getBriefByID = `-- name: GetBriefByID :one
SELECT id, workspace_id, scrape_job_id, product_url, model, status, created_at, updated_at FROM briefs
WHERE id = $1 AND workspace_id = $2
LIMIT 1
`

type GetBriefByIDParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
}

func (q *Queries) GetBriefByID(ctx context.Context, arg GetBriefByIDParams) (Brief, error) {
	row := q.db.QueryRow(ctx, getBriefByID, arg.ID, arg.WorkspaceID)
	var i Brief
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ScrapeJobID,
		&i.ProductUrl,
		&i.Model,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobByID = `-- name: GetJobByID :one
SELECT id, workspace_id, product_url, status, model, brief_json, error_msg, created_at, updated_at, idempotency_key FROM jobs
WHERE id = $1 AND workspace_id = $2
LIMIT 1
`

type GetJobByIDParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
}

func (q *Queries) GetJobByID(ctx context.Context, arg GetJobByIDParams) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByID, arg.ID, arg.WorkspaceID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProductUrl,
		&i.Status,
		&i.Model,
		&i.BriefJson,
		&i.ErrorMsg,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const getVariantForPlayback = `-- name: GetVariantForPlayback :one
SELECT id, job_id, workspace_id, angle, status, fal_request_id, mux_asset_id, mux_playback_id, r2_key, duration_secs, created_at, updated_at, avatar_provider, avatar_job_id FROM variants
WHERE id = $1 AND workspace_id = $2
LIMIT 1
`

type GetVariantForPlaybackParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
}

func (q *Queries) GetVariantForPlayback(ctx context.Context, arg GetVariantForPlaybackParams) (Variant, error) {
	row := q.db.QueryRow(ctx, getVariantForPlayback, arg.ID, arg.WorkspaceID)
	var i Variant
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.WorkspaceID,
		&i.Angle,
		&i.Status,
		&i.FalRequestID,
		&i.MuxAssetID,
		&i.MuxPlaybackID,
		&i.R2Key,
		&i.DurationSecs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvatarProvider,
		&i.AvatarJobID,
	)
	return i, err
}

const getWorkspaceByOrgID = `-- name: GetWorkspaceByOrgID :one
SELECT id, org_id, plan_tier, sub_status, stripe_sub_id, trial_ends_at, created_at, updated_at, monthly_cost_limit_usd, current_month_cost_usd, cost_reset_at FROM workspaces
WHERE org_id = $1
LIMIT 1
`

func (q *Queries) GetWorkspaceByOrgID(ctx context.Context, orgID string) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByOrgID, orgID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.PlanTier,
		&i.SubStatus,
		&i.StripeSubID,
		&i.TrialEndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MonthlyCostLimitUsd,
		&i.CurrentMonthCostUsd,
		&i.CostResetAt,
	)
	return i, err
}

const listBriefAngles = `-- name: ListBriefAngles :many
SELECT id, brief_id, angle, headline, script, cta, voice_tone, created_at FROM brief_angles
WHERE brief_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListBriefAngles(ctx context.Context, briefID pgtype.UUID) ([]BriefAngle, error) {
	rows, err := q.db.Query(ctx, listBriefAngles, briefID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BriefAngle{}
	for rows.Next() {
		var i BriefAngle
		if err := rows.Scan(
			&i.ID,
			&i.BriefID,
			&i.Angle,
			&i.Headline,
			&i.Script,
			&i.Cta,
			&i.VoiceTone,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBriefHooks = `-- name: ListBriefHooks :many
SELECT id, brief_id, hook, created_at FROM brief_hooks
WHERE brief_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListBriefHooks(ctx context.Context, briefID pgtype.UUID) ([]BriefHook, error) {
	rows, err := q.db.Query(ctx, listBriefHooks, briefID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BriefHook{}
	for rows.Next() {
		var i BriefHook
		if err := rows.Scan(
			&i.ID,
			&i.BriefID,
			&i.Hook,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBriefsByWorkspace = `-- name: ListBriefsByWorkspace :many
SELECT id, workspace_id, scrape_job_id, product_url, model, status, created_at, updated_at FROM briefs
WHERE workspace_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListBriefsByWorkspaceParams struct {
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	Limit       int32       `db:"limit" json:"limit"`
	Offset      int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListBriefsByWorkspace(ctx context.Context, arg ListBriefsByWorkspaceParams) ([]Brief, error) {
	rows, err := q.db.Query(ctx, listBriefsByWorkspace, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Brief{}
	for rows.Next() {
		var i Brief
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ScrapeJobID,
			&i.ProductUrl,
			&i.Model,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByWorkspace = `-- name: ListJobsByWorkspace :many
SELECT id, workspace_id, product_url, status, model, brief_json, error_msg, created_at, updated_at, idempotency_key FROM jobs
WHERE workspace_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListJobsByWorkspaceParams struct {
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	Limit       int32       `db:"limit" json:"limit"`
	Offset      int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListJobsByWorkspace(ctx context.Context, arg ListJobsByWorkspaceParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByWorkspace, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProductUrl,
			&i.Status,
			&i.Model,
			&i.BriefJson,
			&i.ErrorMsg,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IdempotencyKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantsByJob = `-- name: ListVariantsByJob :many
SELECT id, job_id, workspace_id, angle, status, fal_request_id, mux_asset_id, mux_playback_id, r2_key, duration_secs, created_at, updated_at, avatar_provider, avatar_job_id FROM variants
WHERE job_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListVariantsByJob(ctx context.Context, jobID pgtype.UUID) ([]Variant, error) {
	rows, err := q.db.Query(ctx, listVariantsByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Variant{}
	for rows.Next() {
		var i Variant
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.WorkspaceID,
			&i.Angle,
			&i.Status,
			&i.FalRequestID,
			&i.MuxAssetID,
			&i.MuxPlaybackID,
			&i.R2Key,
			&i.DurationSecs,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AvatarProvider,
			&i.AvatarJobID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBriefStatus = `-- name: UpdateBriefStatus :one
UPDATE briefs
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, workspace_id, scrape_job_id, product_url, model, status, created_at, updated_at
`

type UpdateBriefStatusParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	Status string      `db:"status" json:"status"`
}

func (q *Queries) UpdateBriefStatus(ctx context.Context, arg UpdateBriefStatusParams) (Brief, error) {
	row := q.db.QueryRow(ctx, updateBriefStatus, arg.ID, arg.Status)
	var i Brief
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ScrapeJobID,
		&i.ProductUrl,
		&i.Model,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateJobStatus = `-- name: UpdateJobStatus :one
UPDATE jobs
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, workspace_id, product_url, status, model, brief_json, error_msg, created_at, updated_at, idempotency_key
`

type UpdateJobStatusParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	Status string      `db:"status" json:"status"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJobStatus, arg.ID, arg.Status)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProductUrl,
		&i.Status,
		&i.Model,
		&i.BriefJson,
		&i.ErrorMsg,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const updateVariantComplete = `-- name: UpdateVariantComplete :one
UPDATE variants
SET status = 'complete',
    mux_asset_id    = $2,
    mux_playback_id = $3,
    r2_key          = $4,
    duration_secs   = $5,
    updated_at      = NOW()
WHERE id = $1
RETURNING id, job_id, workspace_id, angle, status, fal_request_id, mux_asset_id, mux_playback_id, r2_key, duration_secs, created_at, updated_at, avatar_provider, avatar_job_id
`

type UpdateVariantCompleteParams struct {
	ID            pgtype.UUID    `db:"id" json:"id"`
	MuxAssetID    *string        `db:"mux_asset_id" json:"mux_asset_id"`
	MuxPlaybackID *string        `db:"mux_playback_id" json:"mux_playback_id"`
	R2Key         *string        `db:"r2_key" json:"r2_key"`
	DurationSecs  pgtype.Numeric `db:"duration_secs" json:"duration_secs"`
}

func (q *Queries) UpdateVariantComplete(ctx context.Context, arg UpdateVariantCompleteParams) (Variant, error) {
	row := q.db.QueryRow(ctx, updateVariantComplete,
		arg.ID,
		arg.MuxAssetID,
		arg.MuxPlaybackID,
		arg.R2Key,
		arg.DurationSecs,
	)
	var i Variant
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.WorkspaceID,
		&i.Angle,
		&i.Status,
		&i.FalRequestID,
		&i.MuxAssetID,
		&i.MuxPlaybackID,
		&i.R2Key,
		&i.DurationSecs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvatarProvider,
		&i.AvatarJobID,
	)
	return i, err
}

const updateVariantFalRequestID = `-- name: UpdateVariantFalRequestID :one
UPDATE variants
SET fal_request_id = $2,
    updated_at     = NOW()
WHERE id = $1
RETURNING id, job_id, workspace_id, angle, status, fal_request_id, mux_asset_id, mux_playback_id, r2_key, duration_secs, created_at, updated_at, avatar_provider, avatar_job_id
`

type UpdateVariantFalRequestIDParams struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	FalRequestID *string     `db:"fal_request_id" json:"fal_request_id"`
}

func (q *Queries) UpdateVariantFalRequestID(ctx context.Context, arg UpdateVariantFalRequestIDParams) (Variant, error) {
	row := q.db.QueryRow(ctx, updateVariantFalRequestID, arg.ID, arg.FalRequestID)
	var i Variant
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.WorkspaceID,
		&i.Angle,
		&i.Status,
		&i.FalRequestID,
		&i.MuxAssetID,
		&i.MuxPlaybackID,
		&i.R2Key,
		&i.DurationSecs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvatarProvider,
		&i.AvatarJobID,
	)
	return i, err
}

const updateVariantMuxByID = `-- name: UpdateVariantMuxByID :one
UPDATE variants
SET mux_asset_id    = $2,
    mux_playback_id = $3,
    status          = 'complete',
    updated_at      = NOW()
WHERE id = $1
RETURNING id, job_id, workspace_id, angle, status, fal_request_id, mux_asset_id, mux_playback_id, r2_key, duration_secs, created_at, updated_at, avatar_provider, avatar_job_id
`

type UpdateVariantMuxByIDParams struct {
	ID            pgtype.UUID `db:"id" json:"id"`
	MuxAssetID    *string     `db:"mux_asset_id" json:"mux_asset_id"`
	MuxPlaybackID *string     `db:"mux_playback_id" json:"mux_playback_id"`
}

func (q *Queries) UpdateVariantMuxByID(ctx context.Context, arg UpdateVariantMuxByIDParams) (Variant, error) {
	row := q.db.QueryRow(ctx, updateVariantMuxByID, arg.ID, arg.MuxAssetID, arg.MuxPlaybackID)
	var i Variant
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.WorkspaceID,
		&i.Angle,
		&i.Status,
		&i.FalRequestID,
		&i.MuxAssetID,
		&i.MuxPlaybackID,
		&i.R2Key,
		&i.DurationSecs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvatarProvider,
		&i.AvatarJobID,
	)
	return i, err
}

const upsertWorkspace = `-- name: UpsertWorkspace :one
INSERT INTO workspaces (org_id, plan_tier, sub_status, trial_ends_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (org_id) DO UPDATE SET
    plan_tier     = EXCLUDED.plan_tier,
    sub_status    = EXCLUDED.sub_status,
    trial_ends_at = EXCLUDED.trial_ends_at,
    updated_at    = NOW()
RETURNING id, org_id, plan_tier, sub_status, stripe_sub_id, trial_ends_at, created_at, updated_at, monthly_cost_limit_usd, current_month_cost_usd, cost_reset_at
`

type UpsertWorkspaceParams struct {
	OrgID       string             `db:"org_id" json:"org_id"`
	PlanTier    string             `db:"plan_tier" json:"plan_tier"`
	SubStatus   string             `db:"sub_status" json:"sub_status"`
	TrialEndsAt pgtype.Timestamptz `db:"trial_ends_at" json:"trial_ends_at"`
}

func (q *Queries) UpsertWorkspace(ctx context.Context, arg UpsertWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, upsertWorkspace,
		arg.OrgID,
		arg.PlanTier,
		arg.SubStatus,
		arg.TrialEndsAt,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.PlanTier,
		&i.SubStatus,
		&i.StripeSubID,
		&i.TrialEndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MonthlyCostLimitUsd,
		&i.CurrentMonthCostUsd,
		&i.CostResetAt,
	)
	return i, err
}
