// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateJob(ctx context.Context, arg CreateJobParams) (Job, error)
	CreateVariant(ctx context.Context, arg CreateVariantParams) (Variant, error)
	GetJobByID(ctx context.Context, arg GetJobByIDParams) (Job, error)
	GetWorkspaceByOrgID(ctx context.Context, orgID string) (Workspace, error)
	ListJobsByWorkspace(ctx context.Context, arg ListJobsByWorkspaceParams) ([]Job, error)
	ListVariantsByJob(ctx context.Context, jobID pgtype.UUID) ([]Variant, error)
	UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (Job, error)
	UpdateVariantComplete(ctx context.Context, arg UpdateVariantCompleteParams) (Variant, error)
	UpsertWorkspace(ctx context.Context, arg UpsertWorkspaceParams) (Workspace, error)
}

var _ Querier = (*Queries)(nil)
